---
## EPEL Archive location (since EOL)
epel_repo_url: "https://archives.fedoraproject.org/pub/archive/epel/6/x86_64/epel-release-6-8.noarch.rpm"
epel_repo_gpg_key_url: "https://archives.fedoraproject.org/pub/archive/epel/RPM-GPG-KEY-EPEL"

## CIS Hardening Variables
rhel6cis_time_synchronization: chrony
rhel6cis_time_synchronization_servers: ["169.254.169.123"] # Default VPC source
rhel6cis_firewall: "iptables"
# Disable rsyslog/syslog-ng, using cloudwatch
rhel6cis_rule_4_2_3: false
rhel6cis_rule_4_2_1_1: false
rhel6cis_rule_4_2_1_2: false
rhel6cis_rule_4_2_1_3: false
rhel6cis_rule_4_2_1_4: false
rhel6cis_rule_4_2_1_5: false
rhel6cis_rule_4_2_2_1: false
rhel6cis_rule_4_2_2_2: false
rhel6cis_rule_4_2_2_3: false
rhel6cis_rule_4_2_2_4: false
rhel6cis_rule_4_2_2_5: false
rhel6cis_rule_4_3: false
# Disable GRUB tasks
rhel6cis_rule_1_4_2: false
rhel6cis_rule_1_6_1_1: false
rhel6cis_rule_4_1_3: false
# Disable Firewall Tasks, we manage this in app deploy
rhel6cis_rule_3_6_1: false
rhel6cis_rule_3_6_2: false
rhel6cis_rule_3_6_3: false
rhel6cis_rule_3_6_4: false
rhel6cis_rule_3_6_5: false
rhel6cis_rule_5_2_13: false
rhel6cis_rule_5_4_4: false

## ClamAV Variables
clamav_daemon_configuration_changes:
  - regexp: '^.*Example$'
    state: absent
  - regexp: '^.*LocalSocket .*$'
    line: 'LocalSocket {{ clamav_daemon_localsocket }}'
## CloudWatch Agent Variables
cwa_conf_json_file_content: "{{ lookup('file', 'files/cloudwatch-config.json') }}"

## Nagios Variables
nrpe_server_allowed_hosts:
  - 127.0.0.1
nrpe_plugin_packages:
  - nagios-plugins-nrpe
  - nagios-plugins
  - nagios-plugins-disk
nrpe_command:
  check_disk_all:
    script: check_disk
    option: -w 80 -c 90
nrpe_config: 
  dont_blame_nrpe: 0