---
- name: Update System Packages
  yum:
    name: '*'
    state: latest
- name: Install dependencies
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ base_ami_dependencies }}'
- name: Install any additional dependencies supplied
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ additional_packages }}'
