Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel6"
  config.vm.define "rhel6-base"
  config.vm.provider "virtualbox" do |v|
    #Needs a reasonable RAM allocation or ClamAV daemon fails first time start
    v.memory = 4096 
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./vagrant_playbook.yml"
  end
end
