---
- hosts: rhel6-base
  become: true
  collections:
    - ch_collections.base
    - ch_collections.enterpriselinux6
  roles:
    - epel
    - ch_collections.base.os_package_control
    - ch_collections.base.compile_python_source
    - ch_collections.base.pip
    - ch_collections.enterpriselinux6.rhel6_cis
    - ch_collections.enterpriselinux6.clamav
    - ch_collections.base.nagios_nrpe_client
    - cloudwatch_agent
    - ch_collections.base.cloudwatch_agent_helper
  tasks: 
    - name: update iscsi config setting
      lineinfile: 
        path: /etc/iscsi/iscsid.conf
        regexp: '^node.session.timeo.replacement_timeout = 120' 
        line: 'node.session.timeo.replacement_timeout = 5'
        backrefs: yes
    - name: Run multipath config tool to enable multipath and disable user friendly names
      command: mpathconf --enable --with_multipathd y --with_chkconfig y --user_friendly_names n
      args:
        creates: /etc/multipath.conf
    - name: update mpath config to disable friendly names
      lineinfile: 
        path: /etc/multipath.conf
        insertafter: '^defaults*'
        line: 'user_friendly_names no'
    - name: Make sure aws ssm agent is enabled
      service:
        name: amazon-ssm-agent
        state: stopped
        enabled: yes
        