---
collections:
  - name: https://github.com/companieshouse/ansible-collections.git#/ch_collections/enterpriselinux6/
    type: git
    version: 0.1.41
  - name: https://github.com/companieshouse/ansible-collections.git#/ch_collections/base/
    type: git
    version: 0.1.41
  - name: ansible.posix
    version: 1.1.1

roles:
  - src: christiangda.amazon_cloudwatch_agent
    name: cloudwatch_agent
  - src: geerlingguy.repo-epel
    name: epel
